### ISSUE TITLE
Put the base url in a single place

### ISSUE THREAD

**Issue by prighi61** [code4me/4me-sdk-csharp#23]
I suggest to put the base url "https://api.4me.com/v1" or "https://api.4me.qa/v1" in a single place as you can add or replace one.
I need to add the demo url: "https://api.4me-demo.com/v1", but I had to add it in 40 handlers!
Thanks.

Paolo Righi.

**Comment by klaasvandeweerdt** [comment]
Hi Paolo, thanks for the feedback. Make sense to put the base URL in a single place.

**Comment by klaasvandeweerdt** [comment]
A method has been added to return the base URL for quality, production or demo. All handlers have been updated to use that methods instead of the static URL values. Will be part of the next commit.
