### ISSUE TITLE
Added CI class and ci field in CI relation

### ISSUE THREAD

**Issue by prighi61** [code4me/4me-sdk-csharp#24]
Hi Everybody.

I noted the ci field was missing in the Configuration Item Relation class.
I've added CI class as:
    public class CI : BaseItem
    {
        private string label;
        private string name;
        #region label
        [JsonProperty("label")]
        public string Label
        {
            get => label;
            set
            {
                if (label != value)
                    AddIncludedDuringSerialization("label");
                label = value;
            }
        }
        #endregion
        #region name
        [JsonProperty("name")]
        public string Name
        {
            get => name;
            set
            {
                if (name != value)
                    AddIncludedDuringSerialization("name");
                name = value;
            }
        }
        #endregion
    }
Then added to public class ConfigurationItemRelation:
private CI ci;
...
        #region ci
        [JsonProperty("ci")]
        public CI CI
        {
            get => ci;
            set
            {
                if (ci != value)
                    AddIncludedDuringSerialization("ci");
                ci = value;
            }
        }
        #endregion
Now I can get ci data coming from request: GET /cis/:id/ci_relations
as in 
<<Response
Status: 200 OK
[
  {
    "id": "4558",
    "ci": {
      "name": "HP Compaq dc7900 Minitower PC",
      "label": "CMP00021",
      "id": 339
    },
    "relation_type": "parent"
  },
  {
    "id": 324,
    "ci": {
      "name": "HP Compaq dc7900 Minitower PC",
      "label": "CMP00022",
      "id": 340
    },
    "relation_type": "parent"
  }
]>>

Paolo Righi.

**Comment by klaasvandeweerdt** [comment]
Hi Paolo, thank for the info. Adding it to the backlog as well.

**Comment by klaasvandeweerdt** [comment]
@prighi61 
It was already in place but due to an incorrect json attribute reference if failed. The documentation refers to a field call [related_ci_id](https://developer.4me.com/v1/configuration_items/ci_relations/#fields), where it should be `ci` for GET, but `related_ci_id` for POST and PATCH.

The following code now works
```
var ci1 = client.ConfigurationItems.Get(12);
var ci2 = client.ConfigurationItems.Get(13);
client.ConfigurationItems.AddConfigurationItemRelation(ci2, new ConfigurationItemRelation() { CI = ci1, RelationType = ConfigurationitemRelationType.Child });
var relations = client.ConfigurationItems.GetConfigurationItemRelations(ci1);
Console.WriteLine(relations[0].ID);
Console.WriteLine(relations[0].CI.Name);

Update will be part of the next commit.
