### ISSUE TITLE
Extend the Filter class to admit multiple values.

### ISSUE THREAD

**Issue by prighi61** [code4me/4me-sdk-csharp#27]
I needed to define a filter which could include more than one value for field equality as in:
"https://api.4me.com/v1/search?q=unix&types=req,request-template"
I know that it doesn't make sense comparing for greater or lesser multiple value (I can define a new constructor MultiEqualFilter() which is the only one that admits multiple parameters), anyway this implementation satsfies my aim.
I then modified the Filter.cs unit in the following way:
    public class Filter
    {
        private string[] _AttributeValues = { "" };
...
        public string AttributeName { get; } = "";
...
        public string[] AttributeValues
        {
            get
            {
                return _AttributeValues;
            }
        }
...
        public Filter(string attributeName, FilterCondition filter, params string[] attributeValues)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            _AttributeValues = attributeValues;
            this.Condition = filter;
        }
...
        public Filter(string attributeName, FilterCondition filter, params DateTime[] attributeValues)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            int counter = 0;
            Array.Resize<string>(ref _AttributeValues, attributeValues.Length); 
            foreach (DateTime attributevalue in attributeValues)
                _AttributeValues[counter++] = attributevalue.ToString("yyyy-MM-ddTHH:mm:sszzz");
            this.Condition = filter;
        }
...
        public Filter(string attributeName, FilterCondition filter, params short[] attributeValues)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            int counter = 0;
            Array.Resize<string>(ref _AttributeValues, attributeValues.Length);
            foreach (short attributevalue in attributeValues)
                _AttributeValues[counter++] = attributevalue.ToString();
            this.Condition = filter;
        }
...
        public Filter(string attributeName, FilterCondition filter, params int[] attributeValues)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            int counter = 0;
            Array.Resize<string>(ref _AttributeValues, attributeValues.Length);
            foreach (int attributevalue in attributeValues)
                _AttributeValues[counter++] = attributevalue.ToString();
            this.Condition = filter;
        }
...
        public Filter(string attributeName, FilterCondition filter, params long[] attributeValues)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            int counter = 0;
            Array.Resize<string>(ref _AttributeValues, attributeValues.Length);
            foreach (long attributevalue in attributeValues)
                _AttributeValues[counter++] = attributevalue.ToString();
            this.Condition = filter;
        }
...
        public Filter(string attributeName, FilterCondition filter, bool attributeValue)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            _AttributeValues[0] = attributeValue ? "true" : "false";
            this.Condition = filter;
        }
...
        public Filter(string attributeName, FilterCondition filter, params Enum[] attributeValues)
        {
            this.AttributeName = Common.ConvertTo4meAttributeName(attributeName);
            int counter = 0;
            Array.Resize<string>(ref _AttributeValues, attributeValues.Length);
            foreach (Enum attributevalue in attributeValues)
                _AttributeValues[counter++] = Common.ConvertTo4meAttributeName(attributevalue.ToString());
            this.Condition = filter;
        }
...
        private string GetFilter()
        {
            string values = "";
            foreach (string v in AttributeValues)
            {
                if (values.Length > 0)
                    values += ",";
                values += Uri.EscapeDataString(v);
            }
            switch (this.Condition)
            {
                case FilterCondition.GreaterThan:
                    return string.Format("{0}{1}{2}", Uri.EscapeDataString(this.AttributeName), "=>", values);

                case FilterCondition.GreaterThanOrEqualsTo:
                    return string.Format("{0}{1}{2}", Uri.EscapeDataString(this.AttributeName), "=>=", values);

                case FilterCondition.LessThan:
                    return string.Format("{0}{1}{2}", Uri.EscapeDataString(this.AttributeName), "=<", values);

                case FilterCondition.LessThanOrEqualsTo:
                    return string.Format("{0}{1}{2}", Uri.EscapeDataString(this.AttributeName), "=<=", values);

                case FilterCondition.Negation:
                case FilterCondition.NotIn:
                    return string.Format("{0}{1}{2}", Uri.EscapeDataString(this.AttributeName), "=!", values);

                default:
                    return string.Format("{0}{1}{2}", Uri.EscapeDataString(this.AttributeName), "=", values);
            }
        }
    }

Best Regards.

Paolo Righi

**Comment by klaasvandeweerdt** [comment]
@prighi61, thanks for the code. I'm implementing search in as sperate handler to keep the model consistent. So only the `in` and `not in` condition should be extended to support arrays.

**Comment by klaasvandeweerdt** [comment]
@prighi61, Multi value filtering and a separate search has been implemented.
```csharp
var client = new Sdk4meClient(tokens, null, EnvironmentType.Quality, 25, 10);
var results = client.Search.Get("SearchFor", SearchType.Approval, SearchType.Request);
