### ISSUE TITLE
Implementation of an Import function

### ISSUE THREAD

**Issue by prighi61** [code4me/4me-sdk-csharp#34]
Hi Guys,

I'm trying to add an Import function to the SDK. I think I'm near to the solution, however I get a "400: Bad Request" error from the server and I can't find what is wrong. Could you, please, help me to complete the addition of this useful function? Thanks.
The code I added follows.
in the BaseHandler.cs:
        private StreamWriter CSVStreamwriter; // assume 1 import at a time
...
        /// <summary>
        /// Insert a new object in a 4me csv importable file.
        /// </summary>
        /// <param name="csvfilepath">The csv file to create.</param>
        /// <returns>A new instance of the created CsvWriter .</returns>
        public CsvWriter CreateImport(string csvfilepath)
        {
            CSVStreamwriter = new StreamWriter(csvfilepath);
            {
                CsvConfiguration configuration = new CsvConfiguration(CultureInfo.InvariantCulture);
                configuration.IgnoreReferences = true;
                configuration.SkipIDFields = true;

                return new CsvWriter(CSVStreamwriter, configuration);
            }
        }

        /// <summary>
        /// Insert a new object in a 4me csv importable file.
        /// </summary>
        /// <param name="csv">The CsvWriter returned by CreateImport.</param>
        /// <param name="item">The object to create.</param>
        /// <returns>A new instance of the created object.</returns>
        public bool AddToImport(CsvWriter csv, T item)
        {
            //DEFINE DEFAULT VALUE
            bool retval = false;

            //WRITE DEBUG
            DebugWriteLine("AddToImport", "");

            //SHOULD SERIALIZE?
            if (!item.ShouldSendApiRequest())
            {
                DebugWriteLine("POST", "None of the attribute values changed, request canceled");
                return retval;
            }
            try
            {
                item.RemoveIdentifierDuringSerialization();
                serializer.ContractResolver = new Sdk4meContractResolver(item.IncludeDuringSerialization);

                //WRITE CONTENT
                csv.WriteRecord<T>(item);
                csv.NextRecord(); 
                retval = true;
            }
            catch (CsvHelperException ex)
            {
                throw ex;
            }

            item.ResetIncludedDuringSerialization();
            return retval;
        }

        private HttpWebRequest BuildImportWebRequest(string requestUrl, string method, string importtype, string filepath)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(requestUrl);
            request.PreAuthenticate = true;
            currentToken = this.authenticationTokens.Get();
            request.Headers["Authorization"] = currentToken?.BasicAuthenticationToken;
            string boundary = "----------------------------" + DateTime.Now.Ticks.ToString("x");
            request.ContentType = "multipart/form-data; boundary=" + boundary;
            request.Method = method;
            request.KeepAlive = true;
            if (!string.IsNullOrWhiteSpace(accountID))
                request.Headers["X-4me-Account"] = this.accountID;
            long length = 0;
            Stream memStream = new System.IO.MemoryStream();

            byte[] boundarybytes = System.Text.Encoding.ASCII.GetBytes("--" + boundary + "\r\n");
            memStream.Write(boundarybytes, 0, boundarybytes.Length);
            length += boundarybytes.Length;

            string header = "Content-Disposition: form-data; name=\"type\"\r\n" + importtype + "\r\n";

            byte[] headerbytes = System.Text.Encoding.UTF8.GetBytes(header);

            memStream.Write(headerbytes, 0, headerbytes.Length);
            length += headerbytes.Length;

            memStream.Write(boundarybytes, 0, boundarybytes.Length);
            length += boundarybytes.Length;

            string headerTemplate = "Content-Disposition: form-data; name=\"{0}\"; filename =\"{1}\"\r\nContent-Type: application/octet-stream\r\n\r\n";
            header = string.Format(headerTemplate, "file0", Path.GetFileName(filepath));

            headerbytes = System.Text.Encoding.UTF8.GetBytes(header);

            memStream.Write(headerbytes, 0, headerbytes.Length);
            length += headerbytes.Length;

            FileStream fileStream = new FileStream(filepath, FileMode.Open, FileAccess.Read);

            byte[] buffer = new byte[1024];
            int bytesRead = 0;

            while ((bytesRead = fileStream.Read(buffer, 0, buffer.Length)) != 0)
            {
                memStream.Write(buffer, 0, bytesRead);
                length += bytesRead;
            }
            memStream.Write(boundarybytes, 0, boundarybytes.Length);
            length += boundarybytes.Length;

            fileStream.Close();
            request.ContentLength = memStream.Length;

            Stream requestStream = request.GetRequestStream();

            memStream.Position = 0;
            byte[] tempBuffer = new byte[memStream.Length];
            memStream.Read(tempBuffer, 0, tempBuffer.Length);
            memStream.Close();
            requestStream.Write(tempBuffer, 0, tempBuffer.Length);
            requestStream.Close();

            return request;
        }

        /// <summary>
        /// Import data in 4me.
        /// </summary>
        /// <param name="csv">The CsvWriter returned by CreateImport.</param>
        /// <param name="csvfilepath">The csv file to import and delete.</param>
        /// <returns>A new instance of the created object.</returns>
        public bool Import(CsvWriter csv, string csvfilepath)
        {
            //DEFINE DEFAULT VALUE
            bool retval = false;

            csv.Flush();
            csv.Dispose();
            CSVStreamwriter.Dispose();
            CSVStreamwriter = null;

            //BUILD REQUEST URL
            string[] tokens = url.Split('/');
            string importtype = tokens[tokens.Length - 1];
            string requestURL = url.Substring(0, url.Length - importtype.Length) + "import";

            //WRITE DEBUG
            DebugWriteLine("POST", requestURL);

            try
            {
                HashSet<string> hashset = new HashSet<string>();
                HttpWebRequest request = BuildImportWebRequest(requestURL, "POST", importtype, csvfilepath);
                RegisterTime();

                //SEND REQUEST
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                {
                    ... // never reached - I get 400: Bad Request
                }
            }
            catch (WebException ex)
            {
                throw ConvertWebException(ex);
            }
            return retval;
        }

I've even done changes in CSVWriter, I added the SkipIDFields configuration flag.
in "protected virtual void AutoMapMembers()" function I inserted in the
"foreach (var member in members) loop":
    if (configuration.SkipIDFields && String.Compare(member.Name, "ID", true) == 0)
	continue;
so to don't insert ID fields when needed.

Paolo Righi.

**Comment by klaasvandeweerdt** [comment]
@prighi61, I only used the import once since I got in touch with 4me. I remember I got it working, but that was a long time ago. I will try to have a look at it.

**Comment by prighi61** [comment]
Hi @klaasvandeweerdt,

I worked on a solution using libcurl. It works, but I had to change a bit the CSVHelper library, subclassing csvwriter creating customized WriteHeaderField e WriteField methods.
If you know how to write in httpwebRequest an equivalent of the libcurl functions: AddPart, AddFilePart, SetMimePost, maybe we can succed in writing an import function that avoids using libcurl.

Paolo Righi.

**Comment by prighi61** [comment]
Hi @klaasvandeweerdt,

I tried the follwing code and it works using Basic authorization.
I would like to make token authorization (Bearer?) work (moreover the await directive seems do not really wait).
Could you help me a bit, please?

       private async void SendImportWebRequest(string requestUrl, string importtype, string filepath)
        {
            HttpRequestMessage request = new HttpRequestMessage(new HttpMethod("POST"), requestUrl);
            request.Headers.TryAddWithoutValidation("X-4me-Account", "wdc");
            bool bUseToken = false;
            if (bUseToken)
            {
                currentToken = this.authenticationTokens.Get();
                //AuthenticationHeaderValue AuthorizationHeader = new AuthenticationHeaderValue("Bearer", currentToken.Token);
                //request.Headers.Authorization = AuthorizationHeader;
                var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes(currentToken.Token));
                request.Headers.TryAddWithoutValidation("Authorization", $"Bearer {base64authorization}");
            }
            else
            {
                var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes("demo17310:820bf9b4:howard.tanner@widget.com:4me"));
                request.Headers.TryAddWithoutValidation("Authorization", $"Basic {base64authorization}");
            }

            var multipartContent = new MultipartFormDataContent();
            multipartContent.Add(new StringContent(importtype), "type");
            FileStream paramFileStream = new FileStream(filepath, FileMode.Open, FileAccess.Read);
            HttpContent fileStreamContent = new StreamContent(paramFileStream);
            //multipartContent.Add(new ByteArrayContent(File.ReadAllBytes(filepath)), "file", Path.GetFileName(filepath));
            multipartContent.Add(fileStreamContent, "file", Path.GetFileName(filepath));
            request.Content = multipartContent;

            var handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback = (requestMessage, certificate, chain, policyErrors) => true;

            //READ CONTENT
            using (var httpClient = new HttpClient(handler))
            {
                responsemessage = await httpClient.SendAsync(request);
                DebugWriteLine(responsemessage.ToString(), "");
            }
        }

**Comment by prighi61** [comment]
Hi @klaasvandeweerdt,

I tried the follwing code and it works using Basic authorization.
I would like to make token authorization (Bearer?) work (moreover the await directive seems do not really wait).
Could you help me a bit, please?

       private async void SendImportWebRequest(string requestUrl, string importtype, string filepath)
        {
            HttpRequestMessage request = new HttpRequestMessage(new HttpMethod("POST"), requestUrl);
            request.Headers.TryAddWithoutValidation("X-4me-Account", "wdc");
            bool bUseToken = false;
            if (bUseToken)
            {
                currentToken = this.authenticationTokens.Get();
                //AuthenticationHeaderValue AuthorizationHeader = new AuthenticationHeaderValue("Bearer", currentToken.Token);
                //request.Headers.Authorization = AuthorizationHeader;
                var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes(currentToken.Token));
                request.Headers.TryAddWithoutValidation("Authorization", $"Bearer {base64authorization}");
            }
            else
            {
                var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes("demo17310:820bf9b4:howard.tanner@widget.com:4me"));
                request.Headers.TryAddWithoutValidation("Authorization", $"Basic {base64authorization}");
            }

            var multipartContent = new MultipartFormDataContent();
            multipartContent.Add(new StringContent(importtype), "type");
            FileStream paramFileStream = new FileStream(filepath, FileMode.Open, FileAccess.Read);
            HttpContent fileStreamContent = new StreamContent(paramFileStream);
            //multipartContent.Add(new ByteArrayContent(File.ReadAllBytes(filepath)), "file", Path.GetFileName(filepath));
            multipartContent.Add(fileStreamContent, "file", Path.GetFileName(filepath));
            request.Content = multipartContent;

            var handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback = (requestMessage, certificate, chain, policyErrors) => true;

            //READ CONTENT
            using (var httpClient = new HttpClient(handler))
            {
                responsemessage = await httpClient.SendAsync(request);
                DebugWriteLine(responsemessage.ToString(), "");
            }
        }

Paolo Righi.

**Comment by klaasvandeweerdt** [comment]
@prighi61, I know this is already a very old question and I guess you got it working by now. If not, please let me know.
