### ISSUE TITLE
Filtercondition : present request

### ISSUE THREAD

**Issue by cedricbraekevelt** [code4me/4me-sdk-csharp#35]
Hello guys,

Love the work you're doing on the C# SDK. Would it be possible to implement the following filtercondition: "present" https://developer.4me.com/v1/general/filtering/ as seen here? I can't seem to find it in the existing project.

Greetings, Fruity

**Comment by klaasvandeweerdt** [comment]
@fruitychocolate, thanks for the feedback. No clue why the `present` is not included, either I missed it or it did not exist when I implemented the filter class. Same for `empty`.
It will be extended to support multiple values, see #27 in the same push I will include the `present` condition.
The `present` and `empty` can also be achieved by using `equality` or `negation` with an empty value.

**Comment by klaasvandeweerdt** [comment]
@fruitychocolate, the `present` and `empty` have been implemented as well as multi value filtering.
```csharp
Sdk4meClient client = new Sdk4meClient(tokens, null, EnvironmentType.Quality, 100, 5);
client.People.Get(new Filter("SourceID", FilterCondition.Present));
