### ISSUE TITLE
Correction to ConfigurationItemRelation definition.

### ISSUE THREAD

**Issue by prighi61** [code4me/4me-sdk-csharp#39]
Hi to Everybody.

I would like to share a correction with you.
I tried to insert a new ConfigurationItemRelation, but it failed saying that CI can't be NULL.
Following the 4Me documentation (https://developer.4me.com/v1/configuration_items/ci_relations/#fields) you can see that the required fields are related_ci_id and relation_type.
So I changed the following:
        #region related_ci_id

        [JsonProperty("related_ci_id"), Sdk4meIgnoreInFieldSelection()]
        public ConfigurationItem RelatedConfigurationItemID
        {
            get => relatedConfigurationItemID;
            set
            {
                if (relatedConfigurationItemID?.ID != value?.ID)
                    AddIncludedDuringSerialization("related_ci_id_id");
                relatedConfigurationItemID = value;
            }
        }

        [JsonProperty(PropertyName = "related_ci_id_id"), Sdk4meIgnoreInFieldSelection()]
        private long? RelatedCiIdID
        {
            get => (relatedConfigurationItemID != null ? relatedConfigurationItemID.ID : (long?)null);
        }

into to following:
        #region related_ci_id

        [JsonProperty("related_ci"), Sdk4meIgnoreInFieldSelection()]
        public ConfigurationItem RelatedConfigurationItemID
        {
            get => relatedConfigurationItemID;
            set
            {
                if (relatedConfigurationItemID?.ID != value?.ID)
                    AddIncludedDuringSerialization("related_ci_id");
                relatedConfigurationItemID = value;
            }
        }

        [JsonProperty(PropertyName = "related_ci_id"), Sdk4meIgnoreInFieldSelection()]
        private long? RelatedCiIdID
        {
            get => (relatedConfigurationItemID != null ? relatedConfigurationItemID.ID : (long?)null);
        }

and now it works.

Bye.

**Comment by klaasvandeweerdt** [comment]
@prighi61, thank for the feedback. Adding it into the next push.

**Comment by klaasvandeweerdt** [comment]
@prighi61, I had a look in the code but I could not find any reference to an attribute name RelatedConfigurationItemID. I did found a reference to `related_ci_id` in the `ConfigurationItemRelation` class but that already refers to `related_ci_id`. I did a search for `related_ci_id_id` but could not find it either.
