### ISSUE TITLE
Is there a NuGet package available?

### ISSUE THREAD

**Issue by HeinPauwelyn** [code4me/4me-sdk-csharp#40]
I'm wondering if there is a NuGet available for this repository? We want to implement this library to internal software.

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn, for the moment there is not. If I have the time I will look into it, never done this before so it will take some time

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn, replaced the DLL files in the Library folder with a [NuGet package](../tree/master/Library) targeting multiple Frameworks (.Net Framework 4.5.2, .Net Standard 2.1, .Net Core 3.1, .Net 5.0). Still looking to make it available at nuget.org.

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn, version 2 has been published as a [NuGet package](https://www.nuget.org/packages/Sdk4me/).
