### ISSUE TITLE
Access 4me via REST API using C#

### ISSUE THREAD

**Issue by chiaracal** [code4me/4me-sdk-csharp#43]
We would like to access 4me via REST API using C#.
We’ve seen the C# library on github but we’re having issues with authentication, and we’ve noticed that the library hasn’t been updated in a while.
Is it possible that that library is not compatible with the recently introduced 4me authentication methods? Is there an update planned for the library?
Thanks.

**Comment by klaasvandeweerdt** [comment]
@chiaracal, the SDK support old [basic authentication](https://developer.4me.com/v1/#authentication) and recommended [personal access tokens](https://developer.4me.com/v1/#authentication).
I noticed that the dll available in the [Library](https://github.com/code4me/4me-sdk-csharp/tree/master/Library) and in the [Samples](https://github.com/code4me/4me-sdk-csharp/tree/master/Samples) was not the latest version. I'll push later today.

This is a piece of code that works for me
```csharp
AuthenticationTokenCollection tokens = new()
{
    new ("**************************************************************************", AuthenticationType.BearerAuthentication),
    new ("***********************", AuthenticationType.BasicAuthentication),
};

Sdk4meClient client = new(tokens, "sdk-csharp-directory", EnvironmentType.Quality, 100, 1);
var p = client.People.Get(new Filter("PrimaryEmail", FilterCondition.Equality, "name@domain.com"));
```

The library is a free time project and I try to keep it up to data to support most common functionality.

**Comment by chiaracal** [comment]
Thank you!
I use the personal token with the following code
     AuthenticationToken token = new AuthenticationToken("***********");
     Sdk4meClient client = new Sdk4meClient(token, "MyEnvironment");
The connection seems to work properly but when I try to perform a get command, as for example
     Person me = client.People.GetMe();
I receive always the same exception "Unauthorized". I have administrator permissions on 4me.
Now I'm not sure it depends on connection. Do you have any suggestion?
Thanks in advance.

**Comment by chiaracal** [comment]
@klaasvandeweerdt 
I solved adding the BearerAuthentication:
AuthenticationToken token = new AuthenticationToken("***********", AuthenticationType.BearerAuthentication);

Thanks!
