### ISSUE TITLE
Use the Link header for pagination instead of deprecated page parameter

### ISSUE THREAD

**Issue by robbertbrak** [code4me/4me-sdk-csharp#45]
See e.g. https://github.com/code4me/4me-sdk-csharp/blob/master/Source/Sdk4me/Base/BaseHandler.cs#L288 and https://github.com/code4me/4me-sdk-csharp/blob/master/Source/Sdk4me/Base/BaseHandler.cs#L352.

The C# SDK uses `?page=` for pagination, but this is deprecated, as mentioned in the [Developer Documentation Change Log](https://developer.4me.com/v1/general/changelog/) of November 6, 2021. Instead, the SDK should use the links in the Link header (see [here](https://developer.4me.com/v1/general/pagination/)).

This adjustment should be made before support for the `page` parameter is dropped on May 7, 2022.

**Comment by klaasvandeweerdt** [comment]
@robbertbrak, thanks for the notification, changes will be made coming week.

**Comment by robbertbrak** [comment]
Awesome, thanks!
