### ISSUE TITLE
Sdk4me - version 2

### ISSUE THREAD

**Issue by klaasvandeweerdt** [code4me/4me-sdk-csharp#46]
## Sdk4me Version 2
I’m currently rewriting the whole SDK

#### Why
- HttpWebRequest and HttpWebResponse are obsolete in .NET 6
- Different behavior of HttpWebRequest and HttpWebResponse on .NET Core 3.1 and .NET 5
- Adding new entities and updating the existing once (add and remove properties)
- Optimize serialization and deserialization
- Region support for all environments
- Look at your own code a couple of years later

**Comment by fhoeben** [comment]
When rewriting the SDK would it be possible to rewrite it to (also) use the GraphQL API instead? 

This would allow much more powerful/efficient querying capabilities and mutation wise there should not be much/any difference. 

Or does .Net offer sufficient tools to automatically generate a client just taking the GraphQL schema?

**Comment by klaasvandeweerdt** [comment]
@fhoeben, the rewritten version is still using the v1 API. Once I get a hold on GraphQL I probably built a Skd4me.GraphQL library.

**Comment by klaasvandeweerdt** [comment]
The latest version of the Sdk4me has been published, also available as a release.
