### ISSUE TITLE
Changing to GraphQL

### ISSUE THREAD

**Issue by HeinPauwelyn** [code4me/4me-sdk-csharp#48]
On a ticket opened inside 4me one of the reponses from the 4me team was this:

> As you might know, we have introduced the new GraphQL API that has more possibilities. I would recommend to start using GraphQL. We will continue to further extend the capabilities of the 4me GraphQL API, while the REST API will become obsolete at a certain point.
>
> – Wouter Wyns

Is it possible to implement GraphQL to be before on time?

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn, I'm currently exploring the GraphQL API. Main difference is that there are no defaults, meaning a v1 people endpoint returns me a default set of people data. The power of GraphQL is that you have to write a query, that query can return multiple entities in one response, example would be people with their related teams and assigned cis.
I'm currently looking and try to find a way to keep the GraphQL SDK easy to use (set of predefined queries) but in the same time allowing the usage and power of GraphQL queries.

Short answer, I'm currently exploring the GraphQL endpoint and see how I can make a GraphQL SDK version.
No commitment on timing as it is a free time project. Nevertheless I have my own business code that is built on top of the SDK.

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn,
Finally an update on the Skd4me.GraphQL SDK. It took me quite some time to create a proper and generic query model.
The query model supports nested queries and has built-in pagination. It also supports the view and order functionality.

This is an example of a single query searching for people with my name and loading my configuration items, my permissions, and my teams; for each team, it loads the members and for each member their configuration items.

```csharp
PersonQuery query = Query.Person
    .Filter(PersonField.Name, FilterOperator.In, "Klaas", "Klaas Vandeweerdt")
    .Filter(PersonField.CreatedAt, FilterOperator.LessThan, DateTime.Now)
    .Select("*")
    .View(PersonView.All)
    .OrderBy(PersonOrderField.Name, OrderBySortOrder.Ascending)
    .ItemsPerRequest(10)
    .SelectTeams(new TeamQuery()
        .Select(TeamField.Name)
        .ItemsPerRequest(10)
        .SelectMembers(new PersonQuery()
            .ItemsPerRequest(10)
            .Select(PersonField.Name)
                .SelectConfigurationItems(new ConfigurationItemQuery()
                .Select(ConfigurationItemField.Label)
                .ItemsPerRequest(10))))
    .SelectConfigurationItems(new ConfigurationItemQuery()
        .Select(ConfigurationItemField.Label, ConfigurationItemField.Name)
        .ItemsPerRequest(10))
    .SelectPermissions(new PermissionQuery()
        .Select("*")
        .ItemsPerRequest(10));

Sdk4meClient client = new(tokens, "accountID", EnvironmentType.Quality, EnvironmentRegion.EU)
client.MaximumQueryDepthLevelConnections = 5;
var people = await client.Get(query);
var ciLabel = people[0].Teams[0].Members[0].ConfigurationItems[0].Label;
```

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn,
The [.NET SDK for 4me GraphQL](https://github.com/code4me/4me-sdk-graphql-dotnet) is available.
A NuGet will be available by the end of the month.
