### ISSUE TITLE
Add example of pagination to the README

### ISSUE THREAD

**Issue by robinroestenburg** [code4me/4me-sdk-csharp#52]
Hi @klaasvandeweerdt!

Could you add a simple example to the README of how pagination works with the client? E.g. getting `per_page` results and then grabbing the next or previous page.

**Comment by robinroestenburg** [comment]
Looking at the code it seems that the following code
``` csharp
List<Request> requests = client.Requests.Get();
```
will already perform all the pagination for you? By default it will grab 10 pages of 25 items (see https://github.com/code4me/4me-sdk-csharp/blob/master/Source/Sdk4me/Base/BaseHandler.cs#L36-L37).

Setting the `ItemsPerRequest` and `MaximumRecursiveRequests` variables (on the client?) should allow you to change that to your needs. 

A short example would help.

**Comment by klaasvandeweerdt** [comment]
Hi @robinroestenburg,
Indeed, the client handles pagination for you, with a default of 10 pages and 25 items per page.
They are part of the constructor
```csharp
client = new Sdk4meClient(authenticationToken, accountID, EnvironmentType.Production,
    EnvironmentRegion.Global, itemsPerRequest: 25, maximumRecursiveRequests: 10);
```
and can be changed afterwards
```csharp
client.ItemsPerRequest = 100;
client.MaximumRecursiveRequests = 1000;
```
I will add an example to the README
