### ISSUE TITLE
The response is not returning form 4meSDK 

### ISSUE THREAD

**Issue by kirankm111** [code4me/4me-sdk-csharp#55]
Hi Klass,
we have used 4meSDK in application but even if we provided valid authentication token and Account id 
the response is not getting (nothing is returning )

I have downloaded code and debug through tests
I have observed in code thread.sleep() is encountered with 660407241 milliseconds because of this response is not getting 
can you please check from your end once.
<img width="641" alt="Issue123" src="https://user-images.githubusercontent.com/110974093/183885297-67eafe31-bf26-4434-9949-ddaf6ddc6b18.PNG">

**Comment by kirankm111** [comment]
@klaasvandeweerdt can you please check this issue

**Comment by klaasvandeweerdt** [comment]
@kirankm111, I will check it later today.

**Comment by klaasvandeweerdt** [comment]
@kirankm111, Thanks. This is a bug. A mix between milliseconds and ticks. I will make the changes later today and publish version 2.0.3.2 once completed.

**Comment by klaasvandeweerdt** [comment]
@kirankm111, thanks again.
A new release and NuGet package has been deployed.
It also includes an enhancement for custom fields on the team data entity.

**Comment by kirankm111** [comment]
Thanks @klaasvandeweerdt
