### ISSUE TITLE
Get the value from a custumCollection Element

### ISSUE THREAD

**Issue by RobertOsterberg** [code4me/4me-sdk-csharp#58]
Hi Klaas
i am working on a service to get specific requests from 4me and one thing i came across is how to get the Value from a customCollectionElement in a UI Extension. 
So we have a list of folderNames in a UI extension DropdownList and i find the request and i find the customCollection and the customFields but in the array that is returned i only get an ID in the value field. I presume it is a refrence and it needs to be read from another place. See picture for refrence. my code looks like this 

List<Request> details = client.Requests.Get(new Filter("ID", FilterCondition.Equality, request.ID), "custom_fields");
                                CustomFieldCollection cf = details[0].CustomFields;
                                
                                //the keys and values are in the cf variable

                                foreach (string key in cf.Keys)
                                {
                                    
                                }

thank you in advance.

 
![2022-10-13_08-35-04CustomFieldCollections](https://user-images.githubusercontent.com/18688250/195521951-acd17b27-f5b2-4c3c-be8f-a50a16c1f49f.png)

**Comment by klaasvandeweerdt** [comment]
Hi Robert,

I haven't tried to simulate your exact scenario, but the ID in the custom field will be a reference to the custom collection element id. The following code is an example of how to retrieve a custom collection and the related elements.
```csharp
var customCollection = client.CustomCollections.Get(3105);
var elements = client.CustomCollectionElements.Get(new Filter("CustomCollection", FilterCondition.Equality, customCollection.Name));
```
In your case, a direct call to get the custom collection element should be sufficient.
```csharp
long customElementID = details.CustomFields.Get<long>("select_folder");
//or
//long customElementID = Convert.ToInt64(details.CustomFields["select_folder"]);
var element = client.CustomCollectionElements.Get(customElementID);
```
If you would search for a custom collection element multiple times in the same run it may be of interest to first get all custom collection elements and search in your temporary stored collection. This could reduce the number of API calls, which are still limited to 3600 calls per hour.

I also flagged your request as a bug. During testing, I found a bug. The following code fails.
```csharp
var elements = client.CustomCollectionElements.Get("*");
```
In your scenario, there is no need to get all field data, so it will be solved in the next release.

**Comment by RobertOsterberg** [comment]
Thanks again Klaas for your quick responses i will try it out.

**Comment by RobertOsterberg** [comment]
Hi again
i ended up solving it like this

`//Get the request
                                    List<Request> requestDetails = client.Requests.Get(new Filter("ID", FilterCondition.Equality, request.ID), "custom_fields");
                                    //get CustomFields of the request
                                    CustomFieldCollection customFieldCollection = requestDetails[0].CustomFields;

                                    //Get the specific element and parse to INT
                                    var elementID = Convert.ToInt64(customFieldCollection.Values.ElementAt(0));
                                    //Get the elementObject
                                    var elementObject = client.CustomCollectionElements.Get(elementID);
                                    
                                    //Get the stringValue of the customField
                                    var elementName = elementObject.Name;`
![image](https://user-images.githubusercontent.com/18688250/195798957-df8c540e-c6a1-4b77-a0a7-76ebb5539ad5.png)

i know have access to the string value on the customCollectionElement
