### ISSUE TITLE
Requests.GetPeople return Configuration Item

### ISSUE THREAD

**Issue by kvdg** [code4me/4me-sdk-csharp#6]
Hi Klaas,
I was experimenting with this SDK and saw that when you use Requests.GetPeople a configuration item is returned. In the solution I can see that the region has a correct name but just the function is named wrong.

Kind regards
Kevin

**Comment by klaasvandeweerdt** [comment]
Hi Kevin, thanks. The Requests.GetPeople should be Requests.GetConfigurationItems indeed. The latest version contains some other smaller changes which I will push next week.
