### ISSUE TITLE
Error converting value "project_pending" to type 'Sdk4me.RequestStatus'.

### ISSUE THREAD

**Issue by kirankm111** [code4me/4me-sdk-csharp#62]
Hi @klaasvandeweerdt 

While  we are fetching data for Request object from 4me-sdk library 
where it fails to map value "project_pending" to enum RequestStatus because the value "project_pending" is not present in the RequestStatus enum
From the 4me documentation  (https://developer.4me.com/v1/requests/) The valid values for status filed of Request as below
![image](https://user-images.githubusercontent.com/110974093/206742612-111de680-b423-447d-88ab-58d9a1771ebd.png)
Can you please add value "project_pending"  to the RequestStatus Enumaration

**Comment by klaasvandeweerdt** [comment]
@kirankm111, thanks. I already made the change. I will capture the other changes over the weekend and publish the v2.0.5.1 NuGet by Monday.
I also noticed that there is a status missing in the documentation, which is `reservation_pending`. I raised a request to update the documentation.

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111,
Release 2.0.5.1 is available on GitHub and NuGet,
The missing status `reservation_pending` was added to the [documentation](https://developer.4me.com/v1/requests/#fields).
