### ISSUE TITLE
AccountBillableUsers giving 404 not found response

### ISSUE THREAD

**Issue by kirankm111** [code4me/4me-sdk-csharp#63]
Hi @klaasvandeweerdt 

We are getting 404 not found error while getting AccountBillableUsers can you please check once

And for the field supplier_requestID for Request and Task objects we are getting issue like 
"Error retriving field supplier_request_id" 

Can you please check these issues

One more question for Request object  resolution_duration is integer according to documentation but in 4mesdk the ResolutionDuration is Timestamp so do we need to convert timestamp value to integer value in minutes in our code?
**resolution_duration**
Readonly [integer](https://developer.4me.com/v1/general/data_types/) — The number of minutes it took to complete this request, which is calculated as the difference between the created_at and completed_at values.

**Comment by klaasvandeweerdt** [comment]
HI @kirankm111,
The 404 can be related to access rights. Let me check on that and the supplier_requestID as well. Could you share the specific error message from the debug console?
The SDK converts durations to timestamps while reading and back to integers while writing.

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111,
I tested the AccountBillableUsers and it works, make sure the account you are using has the correct access rights.
The ```client.Account.GetBillableUsers();``` send the following request ```GET "https://api.4me-demo.com/v1/account/billable_users?per_page=100"```

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111, There is an issue with the field `supplier_requestID`. This will be solved in the next release.

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111,
The issue with the field `supplier_requestID` has been resolved in release 2.0.7
