### ISSUE TITLE
Does the API implement filtering on custom_fields in a UI Extension?

### ISSUE THREAD

**Issue by RobertOsterberg** [code4me/4me-sdk-csharp#64]
Hi Klaas
i was looking at the 4me delveloper site and came across the HTTP Status Codes that the API gives.
How can i use these in the API Client and handle exceptions?

i tried this approach but can`t get the status codes mentioned on the dev site.
catch (Sdk4meException ex)
            {
                
            }

Hope you can point me in the right direction

Have a great day

**Comment by klaasvandeweerdt** [comment]
Hi @RobertOsterberg,

The Sdk4meException does not contain an HTTP status code. It returns the error message received from the API.
I see a coding difference between the .NET and the .NET Framework version of the client. The .NET version will only throw an exception when the response message from the API contains a JSON message. Where the .NET Framework version also throws an exception with the actual message if there is no JSON body.
Any specific reason why you would need the HTTP code?

Have a nice day as well

**Comment by RobertOsterberg** [comment]
yes i have a Workservice getting requests from 4me and it throws "Rate Limit Exceeded" as an exception and the dev page i can handel the exception in the code by implementing the below.

Once a rate limit window is exceeded an error response is returned and the HTTP header Retry-After indicates how long to wait (in seconds) before making a new request:

**Comment by klaasvandeweerdt** [comment]
When you exceed the rate limit it returns a 429 Too many requests, which should throw a normal HTTP exception.
I would recommend using the values returned via the headers, the [AuthenticationToken](.././blob/f670fa66aaad85871d8e551ac643d05de02ac357/Source/Sdk4me/Base/AuthenticationToken.cs) object contains the `RequestLimit`, `RequestRemaining` and `RequestLimitReset`, although it needs at least one request to actually get the data.
When using the `RemaingRequests` you can limit the number of recurring requests, and `RequestLimitReset` allows you to put the process on hold until that time.

**Comment by RobertOsterberg** [comment]
Ok i will try that thanks for the response.

**Comment by RobertOsterberg** [comment]
Another thing i found is that the 
RequestCompletionReason Enum list does not contain "Declined" and Unsolvable - Unable to solve. as seen in the picture below

![image](https://user-images.githubusercontent.com/18688250/213180880-dfda704a-5573-4099-b963-42e896a5c27f.png)

**Comment by klaasvandeweerdt** [comment]
@RobertOsterberg, thanks for the feedback.
The enum list should contain [Unsolvable](https://github.com/code4me/4me-sdk-csharp/blob/f670fa66aaad85871d8e551ac643d05de02ac357/Source/Sdk4me/Enumerators/Enumerators.cs#L1546), but 3 other completion reasons are missing, `NoReply`, `Rejected` and `Declined`. They have been added and I will push and publish the updates over the weekend.

**Comment by RobertOsterberg** [comment]
Hi again another question. Does the API implement filtering on custom_fields in a UI Extension?
like this one
![image](https://user-images.githubusercontent.com/18688250/213685771-f608db7a-f88b-4669-8f10-f9ca5f42410f.png)

i read about it in this article on the 4me site
https://www.4me.com/blog/custom-field-filters/

we have set it up as described in the article

Have a great day

**Comment by klaasvandeweerdt** [comment]
Hi Robert,
It is not possible, as far as I know, there are no filters available to do this.
The API returns `custom_fields` as a key-value pair object, where the value can be anything.
There are a few ways to narrow down the response using filters and you search the response `CustomFields` using LINQ.
Could you, if possible, describe what you want to achieve? There may be other ways to get there.

**Comment by klaasvandeweerdt** [comment]
Hi @RobertOsterberg,
Removing the bug label, as mentioned in #65 the missing `RequestCompletionReason` values are added in the latest release.

**Comment by klaasvandeweerdt** [comment]
Hi Robert,
The GraphQL API allows [filtering](https://developer.4me.com/graphql/input_object/requestcustomfilter/) on custom fields that have been designated as 'Filterable' in the UI extension. I have updated the [.NET SDK for 4me GraphQL](https://github.com/code4me/4me-sdk-graphql-dotnet)  to include this functionality, but it is not yet available through NuGet. You can either clone the repository or create your own method for this specific feature.

This is an example of the GraphQL query
```graphql
query {
 requests(first: 100 filter: { customFilters: { name: "CustomFilterName", values: ["value1","value2"] } } )
 { nodes { requested } }
}
```

**Comment by RobertOsterberg** [comment]
> Hi Robert, It is not possible, as far as I know, there are no filters available to do this. The API returns `custom_fields` as a key-value pair object, where the value can be anything. There are a few ways to narrow down the response using filters and you search the response `CustomFields` using LINQ. Could you, if possible, describe what you want to achieve? There may be other ways to get there.

Ok so i will try to explain what i am trying to do. So we get multiple requests to add users to AD groups. and i am trying to filter out requests that have a UI Extension field called Automation. This field has two options Automation_Ready and Automation_Completed. but as long as i can`t get to that value i tried using the completed_at field wich contains a DateTime value. but when i try it as a filter it does not find the request. 
So i tried the filter in 4me and it then looks like this
![image](https://user-images.githubusercontent.com/18688250/214010610-919c2b84-a692-4d7d-81f6-ba6998455bc4.png)

the list of requests is just going to get longer and longer as more requests gets submitted and we want to keep it as short as possible

Thanks again!

**Comment by klaasvandeweerdt** [comment]
Hi Robert,
This may help. The example first gets all non-completed requests created based on a specific task template.
The task template contains the UI Extension, so you can assume that it contains the custom fields holding the data. Nevertheless, check if those custom fields exist because the previous version of the UI extension may not contain that field.

```csharp
List<Request> requests = client.Requests.Get(new FilterCollection()
{
    { "Status", FilterCondition.Negation, RequestStatus.Completed },
    { "TemplateID", FilterCondition.Equality, 123}
}, "ID", "CustomFields", "Status");
```
Once you have the data you can loop through all requests and get the values from the `custom_fields`.

```csharp
foreach (Request request in requests) 
{
    Console.WriteLine(request.CustomFields["Automation_Ready"]);
    Console.WriteLine(request.CustomFields["Automation_Completed"]);
}
```
