### ISSUE TITLE
Error while getting data for Request object [Error converting value "rejected" to type 'System.Nullable`1[Sdk4me.RequestCompletionReason]']

### ISSUE THREAD

**Issue by kirankm111** [code4me/4me-sdk-csharp#66]
Hi @klaasvandeweerdt 

We are getting below exception while  getting data for request object

Error converting value "rejected" to type 'System.Nullable`1[Sdk4me.RequestCompletionReason]'. Path '[42].completion_reason', line 1, position

Values are missing in enum RequestCompletionReason
as per document below are the values 

completion_reason: 
solved: Solved - Root Cause Analysis Not Required
workaround: Workaround - Root Cause Not Removed
gone: Gone - Unable to Reproduce
duplicate: Duplicate - Same as Another Request of Customer
withdrawn: Withdrawn - Withdrawn by Requester
no_reply: No Reply - No Reply Received from Customer
rejected: Rejected - Rejected by Approver
conflict: Conflict - In Conflict with Internal Standard or Policy
declined: Declined - Declined by Service Provider
unsolvable: Unsolvable - Unable to Solve

Can you please update values for RequestCompletionReason enum in sdk4me library

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111,

Same as Issue [#64](https://github.com/code4me/4me-sdk-csharp/issues/64#issuecomment-1387429010). This will be resolved in the next release this weekend.

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111 
The Git Release and NuGet 2.0.8 are available.
