### ISSUE TITLE
Add DEV as environment

### ISSUE THREAD

**Issue by RobertOsterberg** [code4me/4me-sdk-csharp#67]
#Enhancement
Can Development be added as an Environment?
We have an DEV, QA and PROD env

//
    // Summary:
    //     A 4me environment type.
    public enum EnvironmentType
    {
        //
        // Summary:
        //     The 4me production environment.
        Production = 0,
        //
        // Summary:
        //     The 4me quality environment.
        Quality = 1,
        //
        // Summary:
        //     The 4me demo environment.
        //     The environment region is obsolete for the 4me demo environment.
        Demo = 2
    }

**Comment by klaasvandeweerdt** [comment]
@RobertOsterberg,
The environment type is used to define the URL of the REST API. 4me only has 3 [environment types](https://developer.4me.com/v1/#service-url), Demo, Quality Assurance, and Production. There are only 3 REST API endpoints (per region).
I assume that what call a DEV environment is a Quality Assurance instance. The rest API endpoint for it is https://api.4me.qa/v1.

To connect to 4me it needs the correct endpoint and the 4me account ID. In the [code base](https://github.com/code4me/4me-sdk-csharp/blob/90abfa8c19dd731887a78f5c28dc905761f7b891/Source/Sdk4me/EnvironmentURL.cs#L16), you can see how that endpoint is built.

The following constructor will use the https://api.4me.qa/v1 endpoint.
```csharp
new Sdk4meClient(tokens, "accountID", EnvironmentType.Quality, EnvironmentRegion.EU);
```

**Comment by RobertOsterberg** [comment]
> @RobertOsterberg, The environment type is used to define the URL of the REST API. 4me only has 3 [environment types](https://developer.4me.com/v1/#service-url), Demo, Quality Assurance, and Production. There are only 3 REST API endpoints (per region). I assume that what call a DEV environment is a Quality Assurance instance. The rest API endpoint for it is https://api.4me.qa/v1.
> 
> To connect to 4me it needs the correct endpoint and the 4me account ID. In the [code base](https://github.com/code4me/4me-sdk-csharp/blob/90abfa8c19dd731887a78f5c28dc905761f7b891/Source/Sdk4me/EnvironmentURL.cs#L16), you can see how that endpoint is built.
> 
> The following constructor will use the https://api.4me.qa/v1 endpoint.
> 
> ```cs
> new Sdk4meClient(tokens, "accountID", EnvironmentType.Quality, EnvironmentRegion.EU);
> ```

Yes that is true, our DEV instance ends with 4me.qa good point
