### ISSUE TITLE
Request,Task values are not filling while getting Timeentry 

### ISSUE THREAD

**Issue by kirankm111** [code4me/4me-sdk-csharp#68]
Hi @klaasvandeweerdt 
The values for Task and Request,ProjectTask values are not filling in the response while getting data for Timeentry object.

The values for the above properties getting from 4me api
![image](https://user-images.githubusercontent.com/110974093/216629356-36879373-a28a-4167-a6a1-16cf8b1afb0b.png)
![image](https://user-images.githubusercontent.com/110974093/216629769-f810e11f-8a2c-4a91-b7c2-2a066c8591c5.png)

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111

I cannot reproduce the issue. I have done the tests on a demo instance.
```csharp
List<TimeEntry> timeEntries = client.TimeEntries.Get();
foreach (TimeEntry entry in timeEntries)
{
    if (entry.Request is null && entry.ProjectTask is null && entry.Task is null)
        throw new NullReferenceException(entry.ID.ToString());
}
```

**Comment by kirankm111** [comment]
Hi @klaasvandeweerdt ,
We are filtering columns with **Sdk4meIgnoreInFieldSelectionAttribute** before sending request  due to this the values are not coming from the response.

if (property.GetCustomAttribute(typeof(Sdk4meIgnoreInFieldSelectionAttribute)) is not null)
                    retval.Remove(property.Name);

 [JsonProperty("task")]
        [Sdk4meIgnoreInFieldSelection]
        public Task Task
        {
            get
            {
                return task;
            }
            set
            {
                task = SetValue("task_id", task, value);
            }
        }

[JsonProperty("request")]
        [Sdk4meIgnoreInFieldSelection]
        public Request Request
        {
            get
            {
                return request;
            }
            set
            {
                request = SetValue("request_id", request, value);
            }
        }

**Comment by klaasvandeweerdt** [comment]
Hi @kirankm111, yes it means that the is not sent as part of the fields parameter. Specifying `request`, `task`, `problem`, or `project_task` returns an `Unknown fields` exception, which is expected behavior. One of those four fields should be returned by default.

**Comment by klaasvandeweerdt** [comment]
@kirankm111, you need the `time_allocation` field to get those values. More information is available in the [documentation](https://developer.4me.com/v1/time_entries/#collection-fields).

> Note that the `problem`, `request`, `task` and `project_task` fields cannot be specified using the [?fields= parameter](https://developer.4me.com/v1/general/field_selection/#collection-of-resources). These fields will appear when the `time_allocation` field is specified.

**Comment by kirankm111** [comment]
Thanks @klaasvandeweerdt  now we got those values
