### ISSUE TITLE
Cannot access to the Custom Fields in the Custom Collection Elements

### ISSUE THREAD

**Issue by ferreiranfactis** [code4me/4me-sdk-csharp#69]
Hi @klaasvandeweerdt 

This related to the [Request#34777891](https://factis.4me.com/requests/34777891)

I cannot access to the custom fields because the CustomCollectionElement object implements “BaseItem” and to have access to the Custom Fields I think the CustomCollectionElement object have to implements “CustomFieldsBaseItem”.

As you can see in the image bellow the Person object implements “CustomFieldsBaseItem” and I have access to the CustomFields by code
![image](https://github.com/code4me/4me-sdk-csharp/assets/133036774/f0f016c0-bef9-4c38-befd-632f6a67798d)

Example of code of Person Custom Fields

```
if (item.CustomFields.Count > 0)
{
	if (item.CustomFields["title"] != null)
	{
		//get Custom Collection Element by ID
		CustomCollectionElement element = client.CustomCollectionElements.Get(new Filter("id", FilterCondition.Equality, item.CustomFields["title"].ToString())).FirstOrDefault();
		newRecord.fac_title = element != null ? element.Name : null;
	}
}
```

If I go to the CustomCollectionElement object, this class implements “BaseItem”.

![image](https://github.com/code4me/4me-sdk-csharp/assets/133036774/d74dbee3-a384-49e6-a90e-feb1f8bf53a5)

It’s possible to do this enhancement ASAP?

Best Regards,
Nuno Ferreira
FACTIS

**Comment by klaasvandeweerdt** [comment]
@ferreiranfactis, thanks for the detailed description. The update has been deployed, and the new NuGet, version 2.1.4,  will be available soon.

**Comment by ferreiranfactis** [comment]
@klaasvandeweerdt thanks for your fast response and code 👍
