### ISSUE TITLE
Problem while accessing projects on the rest api

### ISSUE THREAD

**Issue by JakobHeubl** [code4me/4me-sdk-csharp#70]
Hey @klaasvandeweerdt,
i have the issues that when accessing the rest api endpoint "projects" with your client i get following message:
```[15:45:08 FTL] Could not fetch data from 4me.
Sdk4me.Sdk4meException: Not Found.
   at Sdk4me.BaseHandler`2.SendHttpRequest(HttpRequestMessage requestMessage, T item)
   at Sdk4me.BaseHandler`2.Get(String predefinedFilter, FilterCollection filters, String nextPageUrl, Int32 recursiveRequestCount)
   at Sdk4me.BaseHandler`2.Get(String[] fieldNames)
   at Submission#0.SyncTo4me.sync(String jsonData, String jsonDataMapping) in C:\Users\...\SyncTo4me.csx:line 81
```
The interesting part is, that the problem only exists with that endpoint.
I already contacted 4me and asked if the endpoint is not accessible over the REST API but they assured me, that it should work.
I implemented the endpoint as follows:
```
using Sdk4me;
...
List<Project> projects; 
...
projects = client.Projects.Get();
```
Thanks i advance for the help!

**Comment by klaasvandeweerdt** [comment]
Hi @JakobHeubl
This seems to be an issue with the 4me REST API, I am able to connect to `/v1/projects` on a demo and production instance, but not on QA.

**Comment by JakobHeubl** [comment]
Hey @klaasvandeweerdt,
thanks for your help! 
I will contact 4me again since i did not found any evidence in the documentation that this behaviour is intentional.

**Comment by JakobHeubl** [comment]
Hey @klaasvandeweerdt,
sadly this issue is still present in our QA enviroment. 
I also found the same issue with the endpoint:
``POST /cis/:id/service_instances/:service_instance_id``
Could you look into that more?

I also tried to access the API on the production enviroment but when trying to connect to any endpoint i get the http status code 400 which would indecate, that i send a wrong parameter or a syntax error inside the json i send.
But the error also appears when accessing endpoints like /projects or /produkts - where i do not send any json or parameters besides the default ones.
Interestingly enough appares this issue only on the production and not on the quality enviroment.
Maybe there is an configuration issue but the only thing i change between these two enviroments are the authentication token, account id and enviroment.
Maybe you have an idea, why this happens...

**Comment by klaasvandeweerdt** [comment]
@JakobHeubl, I can do some tests and try to simulate it. I do have a few questions about the config
- Are you using a personal access token or OAuth 2 application client credential grant?
- Is it a connection to a directory account, support domain, or a standard account?

The reason that the `/projects` failed on my account is that I do not have projects in my QA account.

**Comment by JakobHeubl** [comment]
Hello @klaasvandeweerdt,
In the QA environment we are using a OAuth 2 application client credential grant.
In the production environment I had used a personal access token to connect to an standard account.
I switched now to an OAuth 2 application client credential grant and with that it works now.

I added some projects to the instance and the issue does not appear again - like you mentioned.
I didn't expect this.
If there are no projects it would made more sense to get an empty JSON, since nothing special is mentioned in the REST API documentation of 4me.
I will recommend to add a hint about this behavior in the documentation to 4me.

But this leaves me with the a problem i still have:
While connecting to the endpoint `POST /cis/:id/service_instances/:service_instance_id` i also get an 404 not found which i cannot explain.
I know you would prefer using GraphQL but since this would need an other SDK i would need to rework the interface which at the current stage i can't do.
I also tested the endpoint in the production environment and i got the same issue and status code there.

Thanks for your help!

**Comment by klaasvandeweerdt** [comment]
@JakobHeubl,
About the project, In my case, my `project category` and `project risks level` were not configured. Without those two the project functionality is unavailable in the UI and in the API.

I also did a test on linking a configuration item to a service instance and that works. My CI, Service, and Service instance existing the same support domain as I only have one support domain in my QA environment.

```csharp
ConfigurationItem configurationItemLinkedToService = client.ConfigurationItems.Get(12170089);
ConfigurationItem configurationItemNotLinkedNotLinkedToService = client.ConfigurationItems.Get(11824905);
ServiceInstance serviceInstance = client.ServiceInstances.Get(1287998);

//works
client.ConfigurationItems.AddServiceInstance(configurationItemLinkedToService, serviceInstance);
//exception: Validation Failed. Service Instance must belong to the same Service as the Service of the Configuration Item (service_instances).
client.ConfigurationItems.AddServiceInstance(configurationItemNotLinkedNotLinkedToService, serviceInstance);
```
I did notice that when adding a CI successfully the `ConfigurationItems.AddServiceInstance()`  method returned `false` for .NET Framework. This has been resolved and will be available in the next version.

**Comment by JakobHeubl** [comment]
Hey @klaasvandeweerdt,
thanks for the nice conversation we had!
Since every point has been resolved i will close this issue.
