### ISSUE TITLE
AuthenticationToken should be using SecureString from System.Security instead of "string"

### ISSUE THREAD

**Issue by fasteiner** [code4me/4me-sdk-csharp#71]
# Best Practice
It is best practice in PowerShell and C# to use SecureString for sensitive data like passwords or tokens. 

# Change Request
Please change the class Authentication Token accordingly (you can still offer constructors with strings, for backwards compatibility).

**Comment by klaasvandeweerdt** [comment]
@fasteiner, [Microsoft's recommendation](https://learn.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0) is not to use `SecureString`.

> We recommend that you don't use the SecureString class for new development on .NET (Core) or when you migrate existing code to .NET (Core). For more information, see [SecureString shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md).
