### ISSUE TITLE
Update documentation of Sdk4meClient / update ReadMe.md

### ISSUE THREAD

**Issue by fasteiner** [code4me/4me-sdk-csharp#72]
I am trying to build a PowerShell Module, using your SDK, however I came across some inconsistency: 

In your ReadMe, there is an example where to parameters are used (clientid and clientsecret):
<img width="707" alt="image" src="https://github.com/code4me/4me-sdk-csharp/assets/75947402/e9f3c38b-1252-46b2-8937-d29d1a76b49a">

Please change this as it is actually not supported:
<img width="1143" alt="image" src="https://github.com/code4me/4me-sdk-csharp/assets/75947402/2609f332-3dd5-4045-8627-a00020723de3">

code:

```c#
protected override void EndProcessing()
    {
        AuthenticationToken token;
        if (ParameterSetName == "ClientSecret")
        {
            token = new AuthenticationToken(ClientID, ClientSecret);
        }
        else
        {
            token = new AuthenticationToken(BearerToken);
        }

        Sdk4meClient client = new Sdk4meClient(token, AccountID);
        return client;
    }
```

**Comment by klaasvandeweerdt** [comment]
@fasteiner, the example is incorrect. It requires three or four parameters. I will update the Minimum Example.

This is a working example. The region is optional and defaults to the EU region.
```csharp
AuthenticationToken token = new AuthenticationToken("clientID", "clientSecret");
Sdk4meClient client = new(token, "accountID", EnvironmentType.Quality, EnvironmentRegion.AU);
Person me = client.Me.Get();
```
Also nice to hear that you're building a PowerShell module. If you are about to start with it I would recommend using the [.NET SDK for 4me GraphQL](https://github.com/code4me/4me-sdk-graphql-dotnet) instead.
